export const isWebView = window.ReactNativeWebView !== undefined;

export const MESSAGE_TYPES = {
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_ERROR: 'AUTH_ERROR',
  OPEN_EXTERNAL_BROWSER: 'OPEN_EXTERNAL_BROWSER',
  PICK_IMAGES: 'PICK_IMAGES',
  IMAGES_SELECTED: 'IMAGES_SELECTED',
  UPLOAD_PHOTOS: 'UPLOAD_PHOTOS',
  IMAGES_UPLOADED: 'IMAGES_UPLOADED',
  DISCARD_PHOTOS: 'DISCARD_PHOTOS',
} as const;
